package DadosPessoais;

import com.mysql.cj.protocol.Resultset;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class AlterarDados extends javax.swing.JFrame {

    public AlterarDados() {
        initComponents();
    }

    public AlterarDados(String nome,String sobren,String email,String senh,String peso, String idad,String altu,String obje,String id_cli){
        initComponents();
        txtIdcli.setText(id_cli);
        txtNome.setText(nome);
        txtSobrenome.setText(sobren);
        txtEmail.setText(email);
        pswSenha.setText(senh);
        txtPeso.setText(peso);
        txtIdade.setText(idad);
        txtAltura.setText(altu);
        cmbObjetivo.setSelectedItem(obje);
        txtIdcli.setEnabled(false);
        txtEmail.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        lblLogo1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblSobrenome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblKg = new javax.swing.JLabel();
        lbldade = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        lblCm = new javax.swing.JLabel();
        lblObjetivo = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        txtSobrenome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtIdcli = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        pswSenha = new javax.swing.JPasswordField();
        cmbObjetivo = new javax.swing.JComboBox<>();
        bntSalvarAteracao = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Dados");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 102, 0));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(51, 153, 0));
        jPanel3.setLayout(null);

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo1.setText("Saúde e Bem Estar");
        jPanel3.add(lblTitulo1);
        lblTitulo1.setBounds(260, 10, 440, 60);

        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/logosite.png"))); // NOI18N
        jPanel3.add(lblLogo1);
        lblLogo1.setBounds(80, 10, 60, 60);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 950, 82);

        jPanel4.setBackground(new java.awt.Color(51, 153, 0));
        jPanel4.setLayout(null);

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome");
        jPanel4.add(lblNome);
        lblNome.setBounds(60, 60, 110, 40);

        lblSobrenome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSobrenome.setForeground(new java.awt.Color(255, 255, 255));
        lblSobrenome.setText("Sobrenome");
        jPanel4.add(lblSobrenome);
        lblSobrenome.setBounds(60, 120, 100, 40);

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("E-mail");
        jPanel4.add(lblEmail);
        lblEmail.setBounds(60, 180, 100, 40);

        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Senha");
        jPanel4.add(lblSenha);
        lblSenha.setBounds(60, 240, 110, 40);

        lblPeso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPeso.setForeground(new java.awt.Color(255, 255, 255));
        lblPeso.setText("Peso");
        jPanel4.add(lblPeso);
        lblPeso.setBounds(60, 300, 100, 40);

        lblKg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKg.setForeground(new java.awt.Color(255, 255, 255));
        lblKg.setText("KG");
        jPanel4.add(lblKg);
        lblKg.setBounds(310, 300, 50, 40);

        lbldade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbldade.setForeground(new java.awt.Color(255, 255, 255));
        lbldade.setText("Idade");
        jPanel4.add(lbldade);
        lbldade.setBounds(60, 360, 100, 40);

        lblAltura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAltura.setForeground(new java.awt.Color(255, 255, 255));
        lblAltura.setText("Altura");
        jPanel4.add(lblAltura);
        lblAltura.setBounds(60, 420, 100, 40);

        lblCm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCm.setForeground(new java.awt.Color(255, 255, 255));
        lblCm.setText("Cm");
        jPanel4.add(lblCm);
        lblCm.setBounds(310, 420, 40, 40);

        lblObjetivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblObjetivo.setForeground(new java.awt.Color(255, 255, 255));
        lblObjetivo.setText("Qual seu objetivo");
        jPanel4.add(lblObjetivo);
        lblObjetivo.setBounds(10, 480, 150, 40);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel4.add(txtNome);
        txtNome.setBounds(160, 60, 320, 40);
        jPanel4.add(txtAltura);
        txtAltura.setBounds(160, 420, 140, 40);

        txtSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSobrenomeActionPerformed(evt);
            }
        });
        jPanel4.add(txtSobrenome);
        txtSobrenome.setBounds(160, 120, 320, 40);
        jPanel4.add(txtEmail);
        txtEmail.setBounds(160, 180, 320, 40);

        txtIdcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdcliActionPerformed(evt);
            }
        });
        jPanel4.add(txtIdcli);
        txtIdcli.setBounds(160, 10, 320, 40);
        jPanel4.add(txtIdade);
        txtIdade.setBounds(160, 360, 140, 40);

        pswSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswSenhaActionPerformed(evt);
            }
        });
        jPanel4.add(pswSenha);
        pswSenha.setBounds(160, 240, 320, 40);

        cmbObjetivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emagrecer", "Hipertrofia", "Manter Peso" }));
        cmbObjetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbObjetivoActionPerformed(evt);
            }
        });
        jPanel4.add(cmbObjetivo);
        cmbObjetivo.setBounds(160, 480, 320, 40);

        bntSalvarAteracao.setText("Salvar Alteração");
        bntSalvarAteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarAteracaoActionPerformed(evt);
            }
        });
        jPanel4.add(bntSalvarAteracao);
        bntSalvarAteracao.setBounds(170, 550, 270, 40);

        lblId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblId.setText("ID");
        jPanel4.add(lblId);
        lblId.setBounds(60, 20, 50, 25);

        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });
        jPanel4.add(txtPeso);
        txtPeso.setBounds(160, 300, 140, 40);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(60, 100, 604, 624);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 740, 780);

        setSize(new java.awt.Dimension(753, 789));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void cmbObjetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbObjetivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbObjetivoActionPerformed

    private void bntSalvarAteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarAteracaoActionPerformed
        // 1 - Pegar dados do campos 
        String id, no, so, e, s, p, i, a, o;
        id = txtIdcli.getText();
        no = txtNome.getText();
        so = txtSobrenome.getText();
        e = txtEmail.getText();
        s = pswSenha.getText();
        p = txtPeso.getText();
        i = txtIdade.getText();
        a = txtAltura.getText();
        o = cmbObjetivo.getSelectedItem().toString();
        // 2 - Conectar com Banco de dados
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3307/clinica_saude", "root", "p@$$w0rd");
            // 3 - Pegar os dados alterados e devolver para a tabela
            PreparedStatement st = conectar.prepareStatement("UPDATE usuarios SET nome = ?, sobrenome = ?,senha = ?, peso =?, idade = ?, altura = ?, objetivo = ? WHERE id_cli = ?");
            st.setString(1, no);
            st.setString(2, so);
            st.setString(3, s);
            st.setString(4, p);
            st.setString(5, i);
            st.setString(6, a);
            st.setString(7, o);
            st.setString(8, id);
            st.executeUpdate();//Executar a alteração (UPADATE)
            JOptionPane.showMessageDialog(null, "Dados alterados com sucesso");
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }

        dispose();
    }//GEN-LAST:event_bntSalvarAteracaoActionPerformed

    private void txtIdcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdcliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdcliActionPerformed

    private void pswSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswSenhaActionPerformed

    private void txtSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSobrenomeActionPerformed

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSalvarAteracao;
    private javax.swing.JComboBox<String> cmbObjetivo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblCm;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblKg;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblObjetivo;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSobrenome;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lbldade;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtIdcli;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtSobrenome;
    // End of variables declaration//GEN-END:variables
}
