/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Treino;

/**
 *
 * @author User
 */
public class TreinoBMan extends javax.swing.JFrame {

    /**
     * Creates new form TreinoBMan
     */
    public TreinoBMan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblExercicio = new javax.swing.JLabel();
        lblSerie = new javax.swing.JLabel();
        lblRepeticao = new javax.swing.JLabel();
        lblExerc2 = new javax.swing.JLabel();
        lblExerc4 = new javax.swing.JLabel();
        lblExerc1 = new javax.swing.JLabel();
        lblExer5 = new javax.swing.JLabel();
        lblExer3 = new javax.swing.JLabel();
        lblSer2 = new javax.swing.JLabel();
        lblSer3 = new javax.swing.JLabel();
        lblSer4 = new javax.swing.JLabel();
        lblSer1 = new javax.swing.JLabel();
        lblRep4 = new javax.swing.JLabel();
        lblRep1 = new javax.swing.JLabel();
        lblRep3 = new javax.swing.JLabel();
        lblSer5 = new javax.swing.JLabel();
        lblRep5 = new javax.swing.JLabel();
        lblRep2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Treino B");
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 102, 0));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(51, 153, 0));
        jPanel3.setLayout(null);

        lblExercicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblExercicio.setText("Exercicio");
        jPanel3.add(lblExercicio);
        lblExercicio.setBounds(40, 0, 110, 50);

        lblSerie.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSerie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSerie.setText("Serie");
        jPanel3.add(lblSerie);
        lblSerie.setBounds(270, 0, 60, 40);

        lblRepeticao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRepeticao.setText("Repetição");
        jPanel3.add(lblRepeticao);
        lblRepeticao.setBounds(360, 0, 90, 40);

        lblExerc2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExerc2.setForeground(new java.awt.Color(255, 255, 255));
        lblExerc2.setText("Remada Curvada com Barra");
        jPanel3.add(lblExerc2);
        lblExerc2.setBounds(20, 80, 200, 40);

        lblExerc4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExerc4.setForeground(new java.awt.Color(255, 255, 255));
        lblExerc4.setText("Surpman");
        jPanel3.add(lblExerc4);
        lblExerc4.setBounds(20, 160, 200, 40);

        lblExerc1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExerc1.setForeground(new java.awt.Color(255, 255, 255));
        lblExerc1.setText("Puxada na Polia Alta");
        jPanel3.add(lblExerc1);
        lblExerc1.setBounds(20, 40, 200, 40);

        lblExer5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExer5.setForeground(new java.awt.Color(255, 255, 255));
        lblExer5.setText("Good Morning com Barra");
        jPanel3.add(lblExer5);
        lblExer5.setBounds(20, 200, 200, 40);

        lblExer3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExer3.setForeground(new java.awt.Color(255, 255, 255));
        lblExer3.setText("Remada Sentada na Polia");
        jPanel3.add(lblExer3);
        lblExer3.setBounds(20, 120, 200, 40);

        lblSer2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSer2.setForeground(new java.awt.Color(255, 255, 255));
        lblSer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSer2.setText("3 ");
        jPanel3.add(lblSer2);
        lblSer2.setBounds(260, 80, 70, 40);

        lblSer3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSer3.setForeground(new java.awt.Color(255, 255, 255));
        lblSer3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSer3.setText("3 ");
        jPanel3.add(lblSer3);
        lblSer3.setBounds(260, 120, 70, 40);

        lblSer4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSer4.setForeground(new java.awt.Color(255, 255, 255));
        lblSer4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSer4.setText("3 ");
        jPanel3.add(lblSer4);
        lblSer4.setBounds(260, 200, 70, 40);

        lblSer1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSer1.setForeground(new java.awt.Color(255, 255, 255));
        lblSer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSer1.setText("3 ");
        jPanel3.add(lblSer1);
        lblSer1.setBounds(260, 50, 70, 30);

        lblRep4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRep4.setForeground(new java.awt.Color(255, 255, 255));
        lblRep4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRep4.setText("12-15");
        jPanel3.add(lblRep4);
        lblRep4.setBounds(350, 200, 70, 40);

        lblRep1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRep1.setForeground(new java.awt.Color(255, 255, 255));
        lblRep1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRep1.setText("8-12");
        jPanel3.add(lblRep1);
        lblRep1.setBounds(350, 90, 70, 30);

        lblRep3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRep3.setForeground(new java.awt.Color(255, 255, 255));
        lblRep3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRep3.setText("12-15");
        jPanel3.add(lblRep3);
        lblRep3.setBounds(350, 120, 70, 40);

        lblSer5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSer5.setForeground(new java.awt.Color(255, 255, 255));
        lblSer5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSer5.setText("3 ");
        jPanel3.add(lblSer5);
        lblSer5.setBounds(260, 160, 70, 40);

        lblRep5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRep5.setForeground(new java.awt.Color(255, 255, 255));
        lblRep5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRep5.setText("15-20");
        jPanel3.add(lblRep5);
        lblRep5.setBounds(350, 160, 70, 40);

        lblRep2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRep2.setForeground(new java.awt.Color(255, 255, 255));
        lblRep2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRep2.setText("8-12");
        jPanel3.add(lblRep2);
        lblRep2.setBounds(350, 50, 70, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(30, 30, 450, 250);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 56, 510, 360);

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Treino de costas");
        jPanel1.add(lblTitulo);
        lblTitulo.setBounds(130, 0, 260, 50);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/logosite.png"))); // NOI18N
        jPanel1.add(lblLogo);
        lblLogo.setBounds(20, 0, 60, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 509, 60);

        setSize(new java.awt.Dimension(523, 424));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TreinoBMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TreinoBMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TreinoBMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TreinoBMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TreinoBMan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblExer3;
    private javax.swing.JLabel lblExer5;
    private javax.swing.JLabel lblExerc1;
    private javax.swing.JLabel lblExerc2;
    private javax.swing.JLabel lblExerc4;
    private javax.swing.JLabel lblExercicio;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblRep1;
    private javax.swing.JLabel lblRep2;
    private javax.swing.JLabel lblRep3;
    private javax.swing.JLabel lblRep4;
    private javax.swing.JLabel lblRep5;
    private javax.swing.JLabel lblRepeticao;
    private javax.swing.JLabel lblSer1;
    private javax.swing.JLabel lblSer2;
    private javax.swing.JLabel lblSer3;
    private javax.swing.JLabel lblSer4;
    private javax.swing.JLabel lblSer5;
    private javax.swing.JLabel lblSerie;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
