package TelasPrincipais;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author kaue.plfreire
 */
public class Cadastrar extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrar
     */
    public Cadastrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblSobrenome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblKg = new javax.swing.JLabel();
        lbldade = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        lblCm = new javax.swing.JLabel();
        lblObjetivo = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        txtSobrenome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        bntJaTenhoConta = new javax.swing.JButton();
        pswSenha = new javax.swing.JPasswordField();
        cmbObjetivo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 102, 0));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 153, 0));
        jPanel2.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Saúde e Bem Estar");
        jPanel2.add(lblTitulo);
        lblTitulo.setBounds(260, 10, 440, 60);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/logosite.png"))); // NOI18N
        jPanel2.add(lblLogo);
        lblLogo.setBounds(80, 10, 60, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 960, 82);

        jPanel3.setBackground(new java.awt.Color(51, 153, 0));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setLayout(null);

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome");
        jPanel3.add(lblNome);
        lblNome.setBounds(60, 20, 110, 40);

        lblSobrenome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSobrenome.setForeground(new java.awt.Color(255, 255, 255));
        lblSobrenome.setText("Sobrenome");
        jPanel3.add(lblSobrenome);
        lblSobrenome.setBounds(60, 80, 100, 40);

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("E-mail");
        jPanel3.add(lblEmail);
        lblEmail.setBounds(60, 140, 100, 40);

        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Senha");
        jPanel3.add(lblSenha);
        lblSenha.setBounds(60, 200, 110, 40);

        lblPeso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPeso.setForeground(new java.awt.Color(255, 255, 255));
        lblPeso.setText("Peso");
        jPanel3.add(lblPeso);
        lblPeso.setBounds(60, 260, 100, 40);

        lblKg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKg.setForeground(new java.awt.Color(255, 255, 255));
        lblKg.setText("KG");
        jPanel3.add(lblKg);
        lblKg.setBounds(310, 260, 50, 40);

        lbldade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbldade.setForeground(new java.awt.Color(255, 255, 255));
        lbldade.setText("Idade");
        jPanel3.add(lbldade);
        lbldade.setBounds(60, 320, 100, 40);

        lblAltura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAltura.setForeground(new java.awt.Color(255, 255, 255));
        lblAltura.setText("Altura");
        jPanel3.add(lblAltura);
        lblAltura.setBounds(60, 380, 100, 40);

        lblCm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCm.setForeground(new java.awt.Color(255, 255, 255));
        lblCm.setText("Cm");
        jPanel3.add(lblCm);
        lblCm.setBounds(310, 376, 40, 50);

        lblObjetivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblObjetivo.setForeground(new java.awt.Color(255, 255, 255));
        lblObjetivo.setText("Qual seu objetivo");
        jPanel3.add(lblObjetivo);
        lblObjetivo.setBounds(10, 440, 140, 40);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel3.add(txtNome);
        txtNome.setBounds(160, 20, 320, 40);
        jPanel3.add(txtAltura);
        txtAltura.setBounds(160, 380, 140, 40);
        jPanel3.add(txtSobrenome);
        txtSobrenome.setBounds(160, 80, 320, 40);
        jPanel3.add(txtEmail);
        txtEmail.setBounds(160, 140, 320, 40);
        jPanel3.add(txtPeso);
        txtPeso.setBounds(160, 260, 140, 40);
        jPanel3.add(txtIdade);
        txtIdade.setBounds(160, 320, 140, 40);
        jPanel3.add(jTextField8);
        jTextField8.setBounds(160, 380, 140, 40);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCadastrar);
        btnCadastrar.setBounds(170, 500, 300, 40);

        bntJaTenhoConta.setBackground(new java.awt.Color(51, 102, 0));
        bntJaTenhoConta.setForeground(new java.awt.Color(255, 255, 255));
        bntJaTenhoConta.setText("Ja tenho conta");
        bntJaTenhoConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntJaTenhoContaActionPerformed(evt);
            }
        });
        jPanel3.add(bntJaTenhoConta);
        bntJaTenhoConta.setBounds(260, 550, 130, 30);
        jPanel3.add(pswSenha);
        pswSenha.setBounds(160, 202, 320, 40);

        cmbObjetivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------", "Emagrecer", "Hipertrofia", "Manter Peso" }));
        cmbObjetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbObjetivoActionPerformed(evt);
            }
        });
        jPanel3.add(cmbObjetivo);
        cmbObjetivo.setBounds(160, 440, 320, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(170, 110, 604, 624);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 960, 810);

        setSize(new java.awt.Dimension(963, 809));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void bntJaTenhoContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntJaTenhoContaActionPerformed
       dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_bntJaTenhoContaActionPerformed

    private void cmbObjetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbObjetivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbObjetivoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        //1 - Pegar os dados digitados nos campos e guardar em variaveis.    
        String nom, sob, ema, sen, pes, ida, alt, obj,id_cli;
        id_cli = null;
        nom = txtNome.getText();
        sob = txtSobrenome.getText();
        ema = txtEmail.getText();
        sen = pswSenha.getText();
        pes = txtPeso.getText();
        ida = txtIdade.getText();
        alt = txtAltura.getText();
        obj = cmbObjetivo.getSelectedItem().toString();
        // 2 - Conectar ao banco de dados
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3307/clinica_saude", "root","p@$$w0rd");
            // 3 - Enviar os dados para a tabela do Banco de dados
            PreparedStatement st = conectar.prepareStatement("INSERT INTO usuarios VALUES(?,?,?,?,?,?,?,?,?)");
            st.setString(1, id_cli);
            st.setString(2, nom);
            st.setString(3, sob);
            st.setString(4, ema);
            st.setString(5, sen);
            st.setString(6, pes);
            st.setString(7, ida);
            st.setString(8, alt);
            st.setString(9, obj);
            st.executeUpdate();
            // 4 - Enviar mensagem para o usuario
            JOptionPane.showMessageDialog(null, "Usuário cadastrado!");
            // 5 - Limpar os campos
            txtNome.setText("");
            txtSobrenome.setText("");
            txtEmail.setText("");
            pswSenha.setText("");
            txtPeso.setText("");
            txtIdade.setText("");
            txtAltura.setText("");
            txtNome.requestFocus();
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntJaTenhoConta;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JComboBox<String> cmbObjetivo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblCm;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblKg;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblObjetivo;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSobrenome;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lbldade;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtSobrenome;
    // End of variables declaration//GEN-END:variables
}
